### ISSUE TITLE
Could DAG run in ubuntu system?

### ISSUE THREAD

**Issue by zhouxingyu2016** [cihangxie/DAG#1]
Dear Mr. Xie:
Could this repo run in ubuntu?
I've download your geart job DAG and run it in matlab at ubuntu. Although the Segmentation part in the demo is running smoothly, my matlab collapse every time when Detection part is run. Is this repo running only under the windows system?
Thank you for your attention.

**Comment by cihangxie** [comment]
Hi Xingyu,

I wrote this repo in Matlab at Ubuntu, so it should work under Ubuntu environment. I am less sure if it can work under Windows environment.

I have also tested the detection part on my computer today, and it runs okay. Could you please post the error message from Matlab here?

**Comment by rohitsalem** [comment]
Hi @cihangxie I'm trying to reproduce your result, could you please specify the matlab version and other system specifications that you have. I was also curious why did you use the microsoft's caffe rather than the version of caffe from author of the [Faster-RCNN](https://github.com/rbgirshick/caffe-fast-rcnn/tree/faster-rcnn-upstream-33f2445)? I see that both have roi_pooling_layers.

**Comment by cihangxie** [comment]
The matlab version is R2014b, and ubuntu is 14.04.

You can use the Faster-RCNN version caffe, or any version of caffe which contains roi_pooling_layer.

**Comment by rohitsalem** [comment]
@cihangxie Great! Thanks for the info.

**Comment by EveWYT** [comment]
I ecountered the same problem as yours! And I recommend you to install caffe with roi_pooling_layer in ubuntu. The reason why matlab crash is you do not use GPU and the roi_pooling_layer have not implemented on CPU, you can check roi_pooling_layer.cpp and find that. There is not any error information in windows, but in ubuntu, and it helps me find the problem.

**Comment by gmt710** [comment]
@EveWYT ,hi.
I configure matlab in ubuntu.But the error also occurs.

![image](https://user-images.githubusercontent.com/34018741/48692215-348ba900-ec10-11e8-8408-a81a55e745aa.png)

**Comment by gmt710** [comment]
@EveWYT Okay!So upset.Maybe GPU is out of memory, so it can't run.
The terminal output the message:
Check failed: error == cudaSuccess (2 vs. 0)  out of memory.

**Comment by EveWYT** [comment]
https://blog.csdn.net/u010167269/article/details/50703923

**Comment by gmt710** [comment]
@EveWYT hello,Can I get your email or wechat？

**Comment by gmt710** [comment]
@EveWYT ,hi.
I have a good news to share.
Program debugging passed,which is the CPU version on ubuntu.

Thank you very much for your help recently.
