### ISSUE TITLE
matlab crash when change model_select='det_ZF'

### ISSUE THREAD

**Issue by EveWYT** [cihangxie/DAG#2]
I have successfully run 'demo.m' when model_select='seg_fcn_8s' and 'seg_fcn_alexnet', but when i change model_select='det_ZF' and 'det_VGG', matlab crashed. I found that it crash when run into "net = caffe.Net(net_model, net_weights, 'test');", it might because the model and weights do not match? And how can I solve the problem?

**Comment by cihangxie** [comment]
I think it is a problem of caffe (https://github.com/ShaoqingRen/faster_rcnn/issues/73)

You can only run once for detection networks, i.e., you should restart Matlab every time to run the detection networks.

**Comment by EveWYT** [comment]
Thank you so much, and I have found out the problem

**Comment by gmt710** [comment]
@EveWYT ，hello.I met the problem too.How you solve this problem?
Maybe some problem about initial？

**Comment by EveWYT** [comment]
https://github.com/cihangxie/DAG/issues/1#issuecomment-410178368

**Comment by gmt710** [comment]
@EveWYT ，hi.
my environment：
> Matlab2016b
> windows10
> microsoft's caffe

My caffe build is a CPU version.But I can find the file of roi_pooling_layer.cpp.I don't clearly Whether or not I should compile the gpu version of caffe.

**Comment by EveWYT** [comment]
it might because the roi_pooling_layer.cpp does not have backward_cpu implementation. the codes below from roi_pooling_layer.cpp

	template <typename Dtype>
	void ROIPoolingLayer<Dtype>::Backward_cpu(const vector<Blob<Dtype>*>& top,
		const vector<bool>& propagate_down, const vector<Blob<Dtype>*>& bottom) {
			NOT_IMPLEMENTED;
	}

**Comment by gmt710** [comment]
@EveWYT hi,
the roi_pooling_layer.cpp isn't the same as your code.


![image](https://user-images.githubusercontent.com/34018741/48656620-7d056400-ea62-11e8-9389-95f727148849.png)

**Comment by EveWYT** [comment]
Then i recommend you use ubuntu, since the error information is listed in terminal.

**Comment by gmt710** [comment]
@EveWYT .It can be a bit complicated, I did not install matlab in ubuntu, and I allocated ubuntu system memory is relatively small.

**Comment by gmt710** [comment]
@EveWYT ，Let me look for the problem again and decide if I want to reconfigure it in ubuntu.
I really appreciate your prompt reply.

**Comment by EveWYT** [comment]
the code authors realsed can work well if caffe is correctly installed. so i still doubt that there are some problems in your caffe. but there is no information to checkout in windows.

**Comment by gmt710** [comment]
@EveWYT .yes,I used the command line of Windows and ran the demo, but it was still a flash and no other information was prompted.


![image](https://user-images.githubusercontent.com/34018741/48656880-c0150680-ea65-11e8-89cc-271bac1001a6.png)

**Comment by gmt710** [comment]
@EveWYT ，hi.

> Matlab2016b
> windows10
> microsoft's caffe

I recompiled the gpu version of Caffe, but the same error occurred in matlab and the CPU version of Caffe.

![image](https://user-images.githubusercontent.com/34018741/48669003-04230c80-eb35-11e8-996f-3befa664665a.png)

**Comment by gmt710** [comment]
@EveWYT , hi.
if you change model_select='det_ZF'.
I would like to ask the following is how your generate_config.m file is configured.Thanks!!!

**Comment by EveWYT** [comment]
If you are sure that matlab crashes when run into "net = caffe.Net(net_model, net_weights, 'test');
Then it is still the caffe problem, in ubuntu when run 'make caffe' and run DAG codes, there are some problems to modify before correctly run DAG. 
Since you fetch the models seccessfully in your 'prototxt' and 'weight' folder, just change model_select='det_ZF'. can work, no more configuration is needed.
