### ISSUE TITLE
24% mAP when generating 2000 adversarial images

### ISSUE THREAD

**Issue by EveWYT** [cihangxie/DAG#5]
Since the generating process is time-consuming, I only generate 2000 images using ZF07 and test them on ZF07, but I get 24% mAP. The mAP in paper is 3.61%, I don't know what's wrong. I only change the ZF net used in code with my trained ZF07.

**Comment by cihangxie** [comment]
you may try to increase the attack iteration number... usually the attack strength is proportional to the attack iteration number
