### ISSUE TITLE
where is the python version?

### ISSUE THREAD

**Issue by yh960520** [cihangxie/DAG#6]
Hello, is there a python implement of DAG? How can I find it?
Thanks very much

**Comment by cihangxie** [comment]
Thanks for your interest in our work.

Unfortunately, we do not have python version. Alternatively, if you want to attack a segmentation model, you may use the code of the paper "[On the Robustness of Semantic Segmentation Models to Adversarial Attacks](https://github.com/hmph/adversarial-attacks)".
